package gui;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import banco.AcessoBanco;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JTextPane;

/**
 *
 * @author Kyss
 */

public class AlternativeGUI extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * Creates new form GUI
	 */
	public AlternativeGUI() {
                initComponents();
                AcessoBanco banco = new AcessoBanco();
                String cd = banco.mostrarDado("produto");
                textPane.setText(cd);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
        
            
	private void initComponents() {
		jSeparator1 = new javax.swing.JSeparator();
		jSeparator3 = new javax.swing.JSeparator();
		pnlBevelLow = new javax.swing.JPanel();
		lblCodigo = new javax.swing.JLabel();
		lblQntd = new javax.swing.JLabel();
		lblProduto = new javax.swing.JLabel();
		lblCnpj = new javax.swing.JLabel();
		txtCodigo = new javax.swing.JTextField();
		txtProduto = new javax.swing.JTextField();
		txtQntd = new javax.swing.JTextField();
		txtCnpj = new javax.swing.JTextField();
		pnlEtched = new javax.swing.JPanel();
		btnNovo = new javax.swing.JButton();
		btnNovo.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {
				if (txtCodigo.getText().equals("") || txtProduto.getText().equals("") || txtQntd.getText().equals("") || txtCnpj.getText().equals("")){
        			JOptionPane.showMessageDialog(null,"Todos os campos deve ser preenchidos.");
        		}else{
        			String codigo = txtCodigo.getText();
            		String produto = txtProduto.getText(); 
            		String tabela = "produto";
            		String qntd = txtQntd.getText();
            		String cnpj = txtCnpj.getText();           		
            			
    	        	AcessoBanco banco = new AcessoBanco();
    	        	banco.add(codigo, produto, qntd, cnpj, tabela);
                        String cd = banco.mostrarDado("produto");
                        textPane.setText(cd);
        		}
			}
		});
		btnSalvar = new javax.swing.JButton();
		btnSalvar.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent arg0) {

    			String codigo	= txtCodigo.getText();
        		String produto  = "";        		
        		String qntd		= "";
        		String cnpj 	= "";
        		String tabela	= "produto";

        		if (!txtCodigo.getText().equals("")){
        			
        			/*Se for vazio, atribui nulo e e ignorado por updateBanco().*/
        			if (!txtProduto.getText().equals("")){produto = txtProduto.getText();}
        			else {produto = null;}
        			
        			if (!txtQntd.getText().equals("")){qntd = txtQntd.getText();}
        			else {qntd = null;}
        			
        			if (!txtCnpj.getText().equals("")){cnpj = txtCnpj.getText();}
        			else {cnpj = null;}
	            		
        			AcessoBanco banco = new AcessoBanco();
		        	banco.update(codigo,produto,qntd,cnpj,tabela);
                                String cd = banco.mostrarDado("produto");
                                textPane.setText(cd);
        		}else{ JOptionPane.showMessageDialog(null,"Voce precisa especificar o codigo do produto que quer atualizar.");}
        	}
		});
		btnDeletar = new javax.swing.JButton();
		btnDeletar.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
        		if (!txtCodigo.getText().equals("")){
        			String codigo = txtCodigo.getText();
        			String tabela = "produto";

        			AcessoBanco banco = new AcessoBanco();
		        	banco.delete(tabela,codigo);
                                String cd = banco.mostrarDado("produto");
                                textPane.setText(cd);
        		}else{ JOptionPane.showMessageDialog(null,"Voce precisa especificar o codigo do produto que quer apagar.");}
        	}
		});
		jSeparator4 = new javax.swing.JSeparator();
		btnTrocaTabela = new javax.swing.JButton();
		lblVer = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("SISEstoque - Tabela de produtos");
		btnRecarregar = new javax.swing.JButton();
		btnRecarregar.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
                            AcessoBanco banco = new AcessoBanco();
                            String cd = banco.mostrarDado("produto");
                            textPane.setText(cd);
			}
		});
		pnlBevelLow.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
		pnlBevelLow.setPreferredSize(new java.awt.Dimension(370, 170));

		lblCodigo.setText("Codigo");

		lblQntd.setText("Quantidade");

		lblProduto.setText("Produto");

		lblCnpj.setText("CNPJ");

		txtCodigo.setToolTipText("Codigo do produto.");
		txtCodigo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtCodigoActionPerformed(evt);
			}
		});

		txtProduto.setToolTipText("Nome do produto.");

		txtQntd.setToolTipText("Quantidade de produtos.");

		txtCnpj.setToolTipText("CNPJ do fornecedor.");

		javax.swing.GroupLayout pnlBevelLowLayout = new javax.swing.GroupLayout(pnlBevelLow);
		pnlBevelLow.setLayout(pnlBevelLowLayout);
		pnlBevelLowLayout.setHorizontalGroup(pnlBevelLowLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlBevelLowLayout.createSequentialGroup().addContainerGap()
						.addGroup(pnlBevelLowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(lblQntd).addComponent(lblProduto).addComponent(lblCodigo)
								.addComponent(lblCnpj))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(pnlBevelLowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.PREFERRED_SIZE, 60,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtQntd, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.PREFERRED_SIZE, 60,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtCnpj, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.PREFERRED_SIZE, 130,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(txtProduto, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.PREFERRED_SIZE, 250,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(38, 38, 38)));
		pnlBevelLowLayout.setVerticalGroup(pnlBevelLowLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(pnlBevelLowLayout.createSequentialGroup().addContainerGap()
						.addGroup(pnlBevelLowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblCodigo).addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(pnlBevelLowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblProduto).addComponent(txtProduto,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(pnlBevelLowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(lblQntd).addComponent(txtQntd, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(pnlBevelLowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(lblCnpj))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pnlEtched.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		pnlEtched.setPreferredSize(new java.awt.Dimension(370, 48));

		btnNovo.setText("Novo");
		btnNovo.setToolTipText("Nova linha.");

		btnSalvar.setText("Atualizar");
		btnSalvar.setToolTipText("Salvar no banco de dados.");

		btnDeletar.setText("Deletar");
		btnDeletar.setToolTipText("Deletar linha do banco de dados.");

		btnRecarregar.setText("Recarregar");
		btnRecarregar.setToolTipText("Atualizar banco de dados.");

		jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

		btnTrocaTabela.setText("Tabela Fornecedor");
		btnTrocaTabela.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnTrocaTabelaActionPerformed(evt);
			}
		});

		JLabel labelImagem = new JLabel("");
		ImageIcon img = new ImageIcon("imagens/almoxarifado_logo.png");
		labelImagem.setIcon(img);

		javax.swing.GroupLayout pnlEtchedLayout = new javax.swing.GroupLayout(pnlEtched);
		pnlEtchedLayout.setHorizontalGroup(pnlEtchedLayout.createParallelGroup(
				Alignment.LEADING)
				.addGroup(pnlEtchedLayout.createSequentialGroup().addGroup(pnlEtchedLayout
						.createParallelGroup(Alignment.LEADING)
						.addGroup(pnlEtchedLayout.createSequentialGroup().addContainerGap()
								.addGroup(pnlEtchedLayout.createParallelGroup(Alignment.LEADING, false)
										.addComponent(btnNovo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(btnSalvar, GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
								.addPreferredGap(ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
								.addGroup(pnlEtchedLayout.createParallelGroup(Alignment.LEADING, false)
										.addComponent(btnDeletar, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(btnRecarregar, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)))
						.addGroup(pnlEtchedLayout.createSequentialGroup().addGap(26).addComponent(btnTrocaTabela,
								GroupLayout.PREFERRED_SIZE, 149, GroupLayout.PREFERRED_SIZE)))
						.addPreferredGap(ComponentPlacement.UNRELATED)
						.addComponent(jSeparator4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
								GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED)
						.addComponent(labelImagem, GroupLayout.PREFERRED_SIZE, 153, GroupLayout.PREFERRED_SIZE)
						.addGap(6)));
		pnlEtchedLayout
				.setVerticalGroup(
						pnlEtchedLayout
								.createParallelGroup(
										Alignment.LEADING)
								.addGroup(Alignment.TRAILING, pnlEtchedLayout.createSequentialGroup()
										.addGroup(pnlEtchedLayout.createParallelGroup(Alignment.TRAILING)
												.addGroup(pnlEtchedLayout.createSequentialGroup().addContainerGap()
														.addComponent(labelImagem,
																GroupLayout.PREFERRED_SIZE, 148,
																GroupLayout.PREFERRED_SIZE))
												.addGroup(pnlEtchedLayout.createSequentialGroup().addGap(15)
														.addGroup(pnlEtchedLayout.createParallelGroup(Alignment.LEADING)
																.addGroup(pnlEtchedLayout.createSequentialGroup()
																		.addGroup(pnlEtchedLayout
																				.createParallelGroup(Alignment.LEADING)
																				.addGroup(pnlEtchedLayout
																						.createSequentialGroup()
																						.addComponent(btnNovo)
																						.addPreferredGap(
																								ComponentPlacement.UNRELATED)
																						.addGroup(pnlEtchedLayout
																								.createParallelGroup(
																										Alignment.BASELINE)
																								.addComponent(btnSalvar)
																								.addComponent(
																										btnDeletar)))
																				.addComponent(btnRecarregar))
																		.addPreferredGap(ComponentPlacement.RELATED, 37,
																				Short.MAX_VALUE)
																		.addComponent(btnTrocaTabela,
																				GroupLayout.PREFERRED_SIZE, 50,
																				GroupLayout.PREFERRED_SIZE))
																.addComponent(jSeparator4, GroupLayout.PREFERRED_SIZE,
																		GroupLayout.DEFAULT_SIZE,
																		GroupLayout.PREFERRED_SIZE))))
										.addGap(15)));
		pnlEtched.setLayout(pnlEtchedLayout);

		lblVer.setText("SISEstoque alpha v0.0.4b");

		textPane = new JTextPane();
		textPane.setEditable(false);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addComponent(jSeparator3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
				.addGroup(layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(lblVer)
					.addContainerGap(825, Short.MAX_VALUE))
				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
					.addContainerGap()
					.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
					.addGap(40)
					.addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
							.addComponent(pnlBevelLow, GroupLayout.PREFERRED_SIZE, 369, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
							.addComponent(pnlEtched, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
						.addComponent(textPane, GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE))
					.addGap(50))
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
					.addComponent(jSeparator3, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
						.addComponent(pnlEtched, GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
						.addComponent(pnlBevelLow, GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
						.addComponent(jSeparator1, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(textPane, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 393, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					.addComponent(lblVer)
					.addContainerGap())
		);
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtCodigoActionPerformed
	}// GEN-LAST:event_txtCodigoActionPerformed

	private void btnTrocaTabelaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTrocaTabelaActionPerformed
		this.setVisible(false);
		new AlternativeGUI2().setVisible(true);
	}// GEN-LAST:event_btnTrocaTabelaActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AlternativeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AlternativeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AlternativeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AlternativeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AlternativeGUI().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnRecarregar, btnDeletar, btnNovo, btnSalvar, btnTrocaTabela;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator3;
	private javax.swing.JSeparator jSeparator4;
	private javax.swing.JLabel lblCnpj;
	private javax.swing.JLabel lblCodigo;
	private javax.swing.JLabel lblProduto;
	private javax.swing.JLabel lblQntd;
	private javax.swing.JLabel lblVer;
	private javax.swing.JPanel pnlBevelLow;
	private javax.swing.JPanel pnlEtched;
	private javax.swing.JTextField txtCnpj;
	private javax.swing.JTextField txtCodigo;
	private javax.swing.JTextField txtProduto;
	private javax.swing.JTextField txtQntd;
	private JTextPane textPane;
}
