package gui;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;
import banco.AcessoBanco;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;

/**
 *
 * @author Kyss
 */
public class GUI2 extends javax.swing.JFrame {
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form GUI2
     */
    public GUI2() {
        GUI2.Gambis x = new GUI2.Gambis();
        x.initComponents();
        x.btnRecarregarActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code"> 
    @SuppressWarnings("serial")
    
        public class Gambis extends AcessoBanco{
        
	private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblBanco = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        pnlEtched = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnNovo.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		if (txtCnpj.getText().equals("") || txtNome.getText().equals("") || txtEndereco.getText().equals("") || txtTelefone.getText().equals("")){
        			JOptionPane.showMessageDialog(null,"Todos os campos deve ser preenchidos.");
        		}else{
        			String codigo = txtCnpj.getText();
            		String nome = txtNome.getText();        		
            		String endereco = txtEndereco.getText();
            		String telefone = txtTelefone.getText();
            		String tabela = "fornecedor";
                	AcessoBanco banco = new AcessoBanco();
    	        	banco.add(codigo,nome,endereco,telefone,tabela);
        		}
                    btnRecarregarActionPerformed(arg0);
        	}
        });
        btnSalvar = new javax.swing.JButton();
        btnSalvar.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {

    			String codigo 	= txtCnpj.getText();
        		String nome 	= "";        		
        		String endereco = "";
        		String telefone = "";
        		String tabela	= "fornecedor";
        		
        		if (!txtCnpj.getText().equals("")){
        			
        			/*Se for vazio, atribui nulo e e ignorado por updateBanco().*/
        			if (!txtNome.getText().equals("")){nome = txtNome.getText();}
        			else {nome = null;}
        			if (!txtEndereco.getText().equals("")){endereco = txtEndereco.getText();}
        			else {endereco = null;}
        			if (!txtTelefone.getText().equals("")){telefone = txtTelefone.getText();}
        			else {telefone = null;}

        			AcessoBanco banco = new AcessoBanco();
		        	banco.update(codigo,nome,endereco,telefone,tabela);
        		}else{ JOptionPane.showMessageDialog(null,"Voce precisa especificar o CNPJ do fornecedor que quer atualizar.");}
                    btnRecarregarActionPerformed(e);
        	}
        });
        btnRecarregar = new javax.swing.JButton();
        btnRecarregar.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
                    btnRecarregarActionPerformed(e);
                }
        });
        btnDeletar = new javax.swing.JButton();
        btnDeletar.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		if (!txtCnpj.getText().equals("")){
        			String codigo = txtCnpj.getText();
        			String tabela = "fornecedor";

        			AcessoBanco banco = new AcessoBanco();
		        	banco.delete(tabela,codigo);
        		}else{ JOptionPane.showMessageDialog(null,"Voce precisa especificar o CNPJ do fornecedor que quer apagar.");}
                    btnRecarregarActionPerformed(arg0);
        	}
        });
        jSeparator4 = new javax.swing.JSeparator();
        btnTrocaTabela = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        pnlBevelLow = new javax.swing.JPanel();
        lblCnpj = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISEstoque - Tabela de fornecedores");

        tblBanco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblBanco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CNPJ", "Nome", "Endereco", "Telefone"
            }
        ) {
            @SuppressWarnings("rawtypes")
			Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            @SuppressWarnings({ "unchecked", "rawtypes" })
			public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblBanco.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(tblBanco);

        pnlEtched.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlEtched.setPreferredSize(new java.awt.Dimension(370, 48));

        btnNovo.setText("Novo");
        btnNovo.setToolTipText("Nova linha.");

        btnSalvar.setText("Atualizar");
        btnSalvar.setToolTipText("Salvar no banco de dados.");

        btnRecarregar.setText("Recarregar");
        btnRecarregar.setToolTipText("Atualizar banco de dados.");

        btnDeletar.setText("Deletar");
        btnDeletar.setToolTipText("Deletar linha do banco de dados.");

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnTrocaTabela.setText("Tabela Produto");
        btnTrocaTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrocaTabelaActionPerformed(evt);
            }
        });
        
        labelImagem = new JLabel("");
        ImageIcon img = new ImageIcon("imagens/almoxarifado_logo.png"); 
        labelImagem.setIcon(img); 
        javax.swing.GroupLayout pnlEtchedLayout = new javax.swing.GroupLayout(pnlEtched);
        pnlEtchedLayout.setHorizontalGroup(
        	pnlEtchedLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(pnlEtchedLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(pnlEtchedLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(pnlEtchedLayout.createSequentialGroup()
        					.addGroup(pnlEtchedLayout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(btnSalvar, GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        						.addComponent(btnNovo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        					.addPreferredGap(ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
        					.addGroup(pnlEtchedLayout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(btnDeletar, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(btnRecarregar, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        					.addGap(18))
        				.addGroup(pnlEtchedLayout.createSequentialGroup()
        					.addComponent(btnTrocaTabela, GroupLayout.PREFERRED_SIZE, 149, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)))
        			.addComponent(jSeparator4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(labelImagem, GroupLayout.PREFERRED_SIZE, 153, GroupLayout.PREFERRED_SIZE))
        );
        pnlEtchedLayout.setVerticalGroup(
        	pnlEtchedLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(pnlEtchedLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(pnlEtchedLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(pnlEtchedLayout.createSequentialGroup()
        					.addGroup(pnlEtchedLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(btnRecarregar)
        						.addComponent(btnNovo))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(pnlEtchedLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(btnDeletar)
        						.addComponent(btnSalvar)))
        				.addGroup(pnlEtchedLayout.createSequentialGroup()
        					.addGap(148)
        					.addComponent(jSeparator4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addGap(15))
        		.addComponent(labelImagem, GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
        		.addGroup(pnlEtchedLayout.createSequentialGroup()
        			.addContainerGap(113, Short.MAX_VALUE)
        			.addComponent(btnTrocaTabela, GroupLayout.PREFERRED_SIZE, 50, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        pnlEtched.setLayout(pnlEtchedLayout);

        pnlBevelLow.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        pnlBevelLow.setPreferredSize(new java.awt.Dimension(370, 166));

        lblCnpj.setText("CNPJ");

        lblNome.setText("Nome");

        lblEndereco.setText("Endereco");

        lblTelefone.setText("Telefone");

        txtCnpj.setToolTipText("CNPJ do fornecedor.");
        txtCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCnpjActionPerformed(evt);
            }
        });

        txtNome.setToolTipText("Nome do fornecedor.");

        txtEndereco.setToolTipText("Endereço do Fornecedor.");

        txtTelefone.setToolTipText("Telefone do Fornecedor.");
        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBevelLowLayout = new javax.swing.GroupLayout(pnlBevelLow);
        pnlBevelLow.setLayout(pnlBevelLowLayout);
        pnlBevelLowLayout.setHorizontalGroup(
            pnlBevelLowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBevelLowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBevelLowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEndereco)
                    .addComponent(lblNome)
                    .addComponent(lblCnpj)
                    .addComponent(lblTelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBevelLowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(txtNome)
                    .addComponent(txtCnpj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        pnlBevelLowLayout.setVerticalGroup(
            pnlBevelLowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBevelLowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBevelLowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCnpj)
                    .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBevelLowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBevelLowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndereco)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBevelLowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefone))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel1.setText("SISEstoque alpha v0.0.4b");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane2)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(pnlBevelLow, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(pnlEtched, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlEtched, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(pnlBevelLow, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold> 
        
        private void btnRecarregarActionPerformed(java.awt.event.ActionEvent evt) {
                                    Connection conexao = null;
                    try {
                        conexao = DriverManager.getConnection(getUrl(), getLogin(), getSenhaBanco());
                        Statement state = conexao.createStatement();
                        String cd = "";
                        cd = "select * from fornecedor;";
                        rs = state.executeQuery(cd);

                    } catch (SQLException c) {
                        c.printStackTrace();
                        JOptionPane.showMessageDialog(null, "Erro ao tentar conectar.\nErro: " + c);
                    }
                     
        	    DefaultTableModel model = (DefaultTableModel)
                    tblBanco.getModel();

                    for( int i = model.getRowCount() - 1; i >= 0; i-- ) {
                        model.removeRow(i);
                    }
                    
        	    try{        			
        		while(rs.next()){
        			String [] atributos = new String[] {rs.getString("cnpj_fornecedor"), // Talvez seja fora do while
        											   rs.getString("nome_fornecedor"),
        											   rs.getString("endereco"),
        											   rs.getString("telefone")};
        	    	Object[] row = { atributos[0], atributos[1], atributos[2], atributos[3] };
        	    	model.addRow(row);
        			}
        		}
        	    catch(SQLException ex){JOptionPane.showMessageDialog(null,"Erro: ao recarregar. \nSQLException: " + ex.getMessage()+"\nSQLState: " + ex.getSQLState()+"\nVendorError: " + ex.getErrorCode());}
        	    catch(Exception se){JOptionPane.showMessageDialog(null,"Erro ao recarregar.\nErro: "+se);}
        	    try {
                        conexao.close();
                        rs.close();
                    } catch (SQLException c) {
                        c.printStackTrace();
                        JOptionPane.showMessageDialog(null, "Erro ao tentar desconectar.\nErro: " + c);
                    }
        }
        
        
        
    }
    
    private void btnTrocaTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrocaTabelaActionPerformed
        this.setVisible(false);
        new GUI().setVisible(true);
    }//GEN-LAST:event_btnTrocaTabelaActionPerformed

    private void txtCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCnpjActionPerformed

    }//GEN-LAST:event_txtCnpjActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed

    }//GEN-LAST:event_txtTelefoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRecarregar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnTrocaTabela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JPanel pnlBevelLow;
    private javax.swing.JPanel pnlEtched;
    private javax.swing.JTable tblBanco;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    private JLabel labelImagem;
    // End of variables declaration//GEN-END:variables
}
